hwi_oauth:
    # list of names of the firewalls in which this bundle is active, this setting MUST be set
    firewall_names: [main]

    # https://github.com/hwi/HWIOAuthBundle/blob/master/Resources/doc/2-configuring_resource_owners.md
    #resource_owners:
    #    facebook:
    #    type:                facebook
    #    client_id:           '%env(FB_ID)%'
    #        client_secret:       '%env(FB_SECRET)%'
    #        scope:               "email"
    #        options:
    #            display: popup
    #            csrf: true
    resource_owners:
        battle_net:
            type:                oauth2
            client_id:           '%env(BNET_CLIENT_ID)%'
            client_secret:       '%env(BNET_CLIENT_SECRET)%'
            access_token_url:    'https://eu.battle.net/oauth/token'
            authorization_url:   'https://eu.battle.net/oauth/authorize'
            infos_url:           'https://eu.battle.net/oauth/userinfo'
            scope:               "wow.profile"
            user_response_class: HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse
            options:
                use_bearer_authorization: false
            paths:
                identifier: id
                nickname:   username
                realname:   fullname