image: docker:latest

services:
  - docker:dind

#stages:
#  - production
#
#before_script:
#  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
#
#script:
#  stage: production
#  script:
#    - ls -lA
#    - docker build --pull -t $REGISTRY_PATH -f resources/env/prod/Dockerfile .
#    - docker push $REGISTRY_PATH
#  only:
#    - master
