sudo: required

language: python

services:
  - docker

script:
  - echo "TODO"

before_deploy:
  - cp -v engine/deployment/Dockerfile .
  - docker build -t origin-cli-docker engine/deployment/openshift/ #To replace with mapsred/origin-cli-docker
  - chmod +x engine/deployment/deploy.sh

deploy:
  provider: script
  skip_cleanup: true
  script: docker run -v $PWD:/app -w /app
          -v /var/run/docker.sock:/var/run/docker.sock
          -e OPENSHIFT_SERVER=$OPENSHIFT_SERVER
          -e OPENSHIFT_TOKEN=$OPENSHIFT_TOKEN
          -e OPENSHIFT_PROJECT=$OPENSHIFT_PROJECT
          -e OPENSHIFT_REGISTRY=$OPENSHIFT_REGISTRY
          -e APP=$APP
          origin-cli-docker
          /app/engine/deployment/deploy.sh
  on:
    branch: travis
