sudo: required

language: python

services:
  - docker

before_script:
  - cp -v engine/deployment/Dockerfile .
  - docker build -t origin-cli-docker engine/deployment/openshift/
  - docker run -v $PWD:/app -w /app \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -e OPENSHIFT_SERVER=$OPENSHIFT_SERVER \
      -e OPENSHIFT_TOKEN=$OPENSHIFT_TOKEN \
      -e OPENSHIFT_PROJECT=$OPENSHIFT_PROJECT \
      -e APP=$APP \
      -e APP_HOST=$APP_HOST \
      origin-cli-docker \
      echo "test"
    -
    #  - >
#    $DOCKER_IMAGE_RUN \
#      chmod +x ./engine/deployment/deploy.sh \
#      ./engine/deployment/deploy.sh

deploy:
  provider: script
  script: ./engine/deployment/deploy.sh
  on:
    branch: master
